version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: onpe_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: onpe_maac
    ports:
      - "3306:3306"
    volumes:
      # Importa automáticamente tu SQL al iniciar
      - ./Base de datos MAAC ONPE.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: onpe_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/onpe_maac
      DB_USER: root
      DB_PASSWORD: root123
    depends_on:
      db:
        condition: service_healthy
